(* Differential test for the software FP + idiv routines against the C reference.
   [data/fp_vectors.txt] was generated by the C [fp_*]/[idiv] (via the Rust port's
   [tools/gen_fp_vectors.c]); here we replay those inputs through {!Risc_core.Fp}
   and assert bit-identical output. Each line is one of:

     A x y u v result   -> fp_add x y (u=1) (v=1) = result
     M x y result       -> fp_mul x y          = result
     D x y result       -> fp_div x y          = result
     I x y s quot rem   -> idiv x y (s=1)      = { quot; rem }

   all fields hex (no 0x prefix). *)

open Risc_core

let hex s = int_of_string ("0x" ^ s)

(* Like {!Test_harness.eqx} but capping the printed failures at 20 (a systematic
   divergence would otherwise print tens of thousands of lines). *)
let record desc got want =
  incr Test_harness.total;
  if got <> want
  then (
    incr Test_harness.failures;
    if !Test_harness.failures <= 20
    then Printf.printf "FAIL: %s = %08X, expected %08X\n" desc got want)
;;

let () =
  let ic = open_in "data/fp_vectors.txt" in
  Fun.protect
    ~finally:(fun () -> close_in_noerr ic)
    (fun () ->
       try
         while true do
           let line = input_line ic in
           match String.split_on_char ' ' line |> List.filter (fun s -> s <> "") with
           | [ "A"; x; y; u; v; r ] ->
             record
               (Printf.sprintf "fp_add(%s,%s,%s,%s)" x y u v)
               (Fp.fp_add (hex x) (hex y) (u = "1") (v = "1"))
               (hex r)
           | [ "M"; x; y; r ] ->
             record
               (Printf.sprintf "fp_mul(%s,%s)" x y)
               (Fp.fp_mul (hex x) (hex y))
               (hex r)
           | [ "D"; x; y; r ] ->
             record
               (Printf.sprintf "fp_div(%s,%s)" x y)
               (Fp.fp_div (hex x) (hex y))
               (hex r)
           | [ "I"; x; y; s; q; rem ] ->
             let d = Fp.idiv (hex x) (hex y) (s = "1") in
             record (Printf.sprintf "idiv(%s,%s,%s).quot" x y s) d.Fp.quot (hex q);
             record (Printf.sprintf "idiv(%s,%s,%s).rem" x y s) d.Fp.rem (hex rem)
           | [] -> ()
           | _ -> failwith (Printf.sprintf "malformed vector line: %S" line)
         done
       with
       | End_of_file -> ());
  (* An empty or mis-parsed vector file must not pass as "ok: 0 checks" (the committed
     file yields 19,760). *)
  if !Test_harness.total < 10_000
  then (
    Printf.printf
      "FAILED: only %d fp-vector checks ran (vector file truncated?)\n"
      !Test_harness.total;
    exit 1);
  Test_harness.summary "fp-vector checks"
;;
