(** The [.packonly] manifest (port of [host_tools::packonly]). *)

module StringSet = Set.Make (String)

let file_name = ".packonly"

let parse text =
  String.split_on_char '\n' text
  |> List.fold_left
       (fun acc line ->
          let content =
            match String.index_opt line '#' with
            | Some i -> String.sub line 0 i
            | None -> line
          in
          let name = String.trim content in
          if name = "" then acc else StringSet.add name acc)
       StringSet.empty
;;

let render names =
  "# .packonly — files packed into the image as-is, never compiled.\n\
   # Everything else in this directory is compiled as Oberon source.\n\
   # An empty list compiles everything. Regenerated by extract-source.\n"
  ^ String.concat "" (List.map (fun name -> name ^ "\n") (StringSet.elements names))
;;
